title: "Cidade Bonfim"
description: "Sistema de Governan√ßa TPE + IAM + Dreieinheit"
theme: null

collections:
  pages:
    output: true

markdown: kramdown

plugins:
  - jekyll-seo-tag

url: "https://a-bonfim-tech.github.io"
baseurl: "/cidade-bonfim-governanca"

